try :
    a = int(input("enetr a no. : "))
    print(a)
except Exception as e:
    print(e)

print("code successfully executed !!")