try :
    a = int(input("enetr a no. : "))
    print(a)
except Exception as e:
    print(e)
else: 
    print("code successfully executed !!")  #else runs when try is executed sucessfully